# Generated by Django 2.1.3 on 2018-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
